version: '3.3'
services:
    web:
        image: "qianbitou/nginx-1.14.2:1.2"
        container_name: web
        volumes:
            - "./nginx/conf/php.conf:/usr/local/webserver/nginx/conf/php.conf"
            - "./nginx/conf/vhosts/www.conf:/usr/local/webserver/nginx/conf/vhosts/www.conf"
            - "./advanced:/data/web/yii2"
        ports:
            - "8000:80"
            - "8001:81"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: "qianbitou/php70-fpm:1.1"
        container_name: php
        volumes:
            - "./advanced:/data/web/yii2"
            - "./scripts/run.sh:/root/run.sh"
        ports:
            - "9000:9000"
        restart: always
    composer:
        image: "qianbitou/composer"
        container_name: composer
        volumes:
            - "./advanced:/home/www/app"
        command: update
    mysqldb:
        image: "centos/mysql-56-centos7"
        container_name: mysqldb
        restart: always
        # env_file:
        #     - ".env"
        environment:
            - MYSQL_DATABASE=yii2
            - MYSQL_USER=yii
            - MYSQL_PASSWORD=Yii123456
        ports:
            - "3306:3306"
