apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      items:
      # username secret 存储在 /etc/foo/my-group/my-username 文件中而不是 /etc/foo/username 中
      # password secret 没有被映射
      - key: username
        path: my-group/my-username
