apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      # mountPath 为您想要该 secret 出现的尚未使用的目录
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
	  # secretName 必须等于 secret 对象的名字
      secretName: mysecret
