db:
   container_name: my-db-container
   image: csphere/mysql:5.5
   ports: 
     - "3306:3306"
   volumes:
     - /root/my-db:/var/lib/mysql

web:
   container_name: my-web-container
   image: csphere/hello:1.0
   ports:
      - "80:8080"
   environment:
      - DB_HOST=172.17.42.1
