filebeat.modules:
- module: nginx
  access:
    enabled: true
    var.paths: ["/data/logs/access_*.log"]
  error:
    enabled: true
    var.paths: ["/data/logs/error_*.log"]
output.elasticsearch:
  hosts: ["10.30.4.130:9200"]
  username: "elastic"
  password: "qianbitou2017"
  index: "filebeat-%{+yyyy.MM.dd}"
  template.enabled: true
  template.name: "filebeat"
  template.path: "${path.config}/filebeat.template.json"
  template.overwrite: false
