apiVersion: v1      //描述RC对象的版本是v1
kind: ReplicationController    //我现在在声明RC对象
metadata:     //metadata中的是对此RC对象描述信息
  name: myweb      //此RC对象在default命名空间中名为myweb，同一个命名空间中的命名一定是不同的
spec:     //spec中是对RC对象的具体描述
  replicas: 5    //我要创建5个副本，单位当然是pod
  selector:      //选择器，用来选择对象的
    app: myweb    //我选择了标签为app: myweb的pod
  template:     //模版，以下用来描述创建的pod的模版
    metadata:   //对pod模版描述的元数据
      labels:      //给以下的东西打上标签，以让selector来选择
        app: myweb   //给pod模版打上app: myweb这样的标签
    spec:             //对pod模版的具体描述
      containers:         //以下就是要放入pod模版中的容器了
      - image: kubeguide/tomcat-app:v1    //选择镜像
        name: myweb         //容器名
        resources:           //给该容器分配的资源大小
          limits:
            cpu: "2"
            memory: 4Gi
        ports:         //容器端口号
        - containerPort: 8080         
        env:          //给该容器设置环境变量，这里就可以将mysql与我们的tomcat连接
        - name: MYSQL_SERVICE_HOST
          value: 'mysql'
        - name: MYSQL_SERVICE_PORT
          value: '3306'
