version: "3.6"
services:
  web:
    image: zhl/get-started:v1
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8101:80"
    networks:
      - webnet
networks:
  webnet:
