#!/bin/bash 

# Simple Redis init.d script conceived to work on linux systems 

REDISPORT=6379
EXEC=/usr/local/bin/redis-server
CLIEXEC=/usr/local/bin/redis-cli 

PIDFILE=/var/run/redis_${REDISPORT}.PID 
CONF="/etc/redis/${REDISPORT}.conf"

case "$1" in 
start)
    if [ -f $PIDFILE ];then
        echo "$PIDFILE exits, process is already running or crashed"
    else
        echo "Starting Redis server ..."
        $EXEC $CONF &
    fi
    ;;
stop)
    if [ ! -f $PIDFILE ];then
        echo "$PIDFILE does not exits, process is not running "
    else
        PID=$(cat $PIDFILE) 
        echo "Stopping Redis server ..."
        $CLIEXEC -p $REDISPORT shutdown
        while [ -x /proc/$(PID) ]
        do 
            echo "Waiting for Redis to shutdown ..."
            speed 1 
        done
        echo "Redis stopped"
    fi
    ;;
*)
    echo "Please use start or stop as first argument"
    ;;
esac

